name: Publish viewer to NPM
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build & publish
      - uses: actions/setup-node@v1 # It does setup of .npmrc file to publish to npm
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
        working-directory: viewer
        run: |
          yarn
          yarn build:prod
          cd dist
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
